name: CI
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db: 
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: learn_ci_cd_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install PostgreSQL client
        run: sudo apt update && sudo apt -yqq install libpq-dev postgresql-client
      - uses: actions/checkout@v3
      - name: Lock platform
        run: bundle lock --add-platform x86_64-linux
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Load schema
        run: bundle exec rails db:schema:load --trace
      - name: Run tests
        run:  bundle exec rails test 